[project]
name = "curricubook"
version = "0.1.0"
description = "Tool to generate fancy work and education documents in several formats, lengths and styles"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.11.9",
    "toml>=0.10.2",
]
