[project]
name = "curricubook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-appimage>=1.3.0",
    "ruff>=0.11.9",
]
